config/routes.rb
Rails.application.routes.draw do

  get 'comments/new'

  get 'posts/new'

  root 'sessions#new'
  
  resources :sessions
  
  resources :users do
    resources :posts
  end
  
  resources :users do
    member do 
        post 'add_friend'
        get 'search_friend'
    end
  end
  
  resources :posts do 
      resources :comments
  end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
    belongs_to :user
end

app/models/friend.rb
class Friend < ActiveRecord::Base
    belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments , dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :friends
    has_many :posts
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
    
    helper_method :current_user, :logged_in?

    def current_user
      @current_user ||= User.find_by(:id => session[:user_id])
    end

   def logged_in?
     current_user != nil
   end
   
   
   private
 
  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to root_path
    end
  end
  
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
  
  def create 
    @comment = Comment.new
    @comment.body = comment_params[:body]
    @comment.user_id = session[:user_id]
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to :users
    else
      render plain: 'failed'
    end
  end
  
  private 
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new
  end
  
  def create
    @post = Post.new
    @post.body = post_params[:body]
    
    @post.user_id = params[:user_id]
    if @post.save
      redirect_to users_path
    else
      render 'new' 
    end
  end
  
  def destroy
    @post = Post.find_by_id(params[:id])
    @post.delete
    redirect_to users_path
  end
  
  def edit
    @post = Post.find_by_id(params[:id])
    @user = current_user
  end
  
  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end
  
  private
  
  def post_params
    params.require(:post).permit(:body , :id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to users_path
    end
  end
  
  def create
    @user = User.where("email_id = ?  AND password = ? " , session_params[:email_id] , session_params[:password])
    
    if @user.count == 1
      session[:user] = @user.find_by(1)
      session[:user_id] = @user.find_by(1).id
      redirect_to users_path
    else
      session[:user] = nil
      session[:user_id] = nil
      render 'new'
    end
  end
  
  def destroy
    session[:user] = nil
    session[:user_id] = nil
    redirect_to new_session_path
  end
  
  private
  
  def session_params
    params.require(:session).permit(:email_id , :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :require_login
  
  
  def index
    if logged_in?
      @user = current_user
      @user_ids = Friend.where('friend_id = ?' , @user.id).select('user_id')
      @friend_ids = Friend.where('user_id = ? ' , @user.id).select('friend_id')
      @friends = User.where('id IN (?) OR id IN (?)',@user_ids,@friend_ids).select('first_name')
      @posts = Post.where('user_id IN (? , ?)' , @friends.ids , @user.id)
      @count = @posts.count
      @comments = Comment.where('post_id IN (?)' , @posts.ids)
      @search_user = User.find_by_id(current_user.id)
    else
      redirect_to root_path
    end
  end

  def new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user] = @user
      session[:user_id] = @user.id
      #render plain: user_params
      
      redirect_to users_path
    else
      render 'new'
    end
  end
  
  def show
      @user_curr = current_user
      
      @user = User.find_by_id(params[:id])
      @friend1 = Friend.where('user_id = ? AND friend_id = ?  ' , @user_curr.id , @user.id)
      @friend2 = Friend.where('user_id = ? AND friend_id = ? ' , @user.id , @user_curr.id)
      @is_friend = true
      
      if session[:user_id].to_s != params[:id].to_s
        if @friend1.count == 1 || @friend2.count == 1 
          @is_friend = true
        else
          @is_friend = false
        end
      else
        @is_friend = true
      end
  end
  
  def add_friend
    @friend = Friend.new()
    @friend.friend_id = params[:id]
    @friend.user_id = session[:user_id]
    if @friend.save
      redirect_to root_path
    else
      render plain: 'Request failed.'
    end
  end
  
  def search_friend
    search_string = params[:search]
    if search_string != nil
      @searched_friends = User.where('first_name LIKE ?', "#{search_string}%")
    else
      @searched_friends = User.all
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:first_name , :email_id , :password , :mobile_number , :college)
  end

  def show_params
    params.require(:user).permit(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  

<%= yield %>

app/views/posts/edit.html.erb
<title>Edit</title>
</head>
<body>
<h1>Editing post</h1>

<%= form_for :post, url: user_post_path(@user , @post) , method: :patch do |f| %>
  <p>
    <%= f.label :Body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</body>
</html>

app/views/posts/new.html.erb
<title>New</title>
</head>
<body>
<%= form_for([@network, @network.users.build]) do |f|%>
<p>
    <%= f.label :Full_Name%>
    <%= f.text_field :fullname %>
    <%= f.submit %>
</p>

<%  end  %>
</body>
</html>

app/views/users/index.html.erb
<title>Home</title>
</head>
<body>
<% if logged_in? -%>
    Welcome, 
    <%= link_to current_user.email_id , users_path %>
    <%= link_to 'Logout', session_path(current_user) , method: :delete , data: {confirm: "Are you sure?"} %>
<% end %>


<%= form_for( @search_user, :url => search_friend_user_path( @search_user ), :html => { :method => :get } ) do |f| %>
 <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>



<h2>What is in your mind.</h2>
<%= form_for([@user, @user.posts.build]) do |f|%>
<p>
    <%= f.label :body %>
    <%= f.text_field :body %>
    <%= f.submit %>
</p>
<%  end  %>


<table>                         
  <tr>                          
    <th>Posts 
        <h2>COUNT <%=  @posts.count  %></h2>
    </th>
  </tr>
<% @posts.each do |post| %> 
  
  <tr>
    <td>Post By : <%= User.find_by_id(post.user_id).first_name %></td>
  </tr>
  <tr>
      <td>Post body <%= post.body %></td>
  </tr>
  <tr>
    <% if post.user_id == session[:user_id] %>
    <td>
        <%= link_to 'Destroy', user_post_path(@user , post)  , method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
    <td>
      <%= link_to "Edit", edit_user_post_path(@user , post)  %>
    </td>
        
    <% end %>
  </tr>
  <tr>

    <td>
      <% @post_comments = @comments.where('post_id = ? ' , post.id) %>
      <p>Comments Count : <%= @post_comments.count %> </p>
      <br>
      <% @post_comments.each do |f|  %>
      <% @tmp_user = User.find_by_id(f.user_id) %>
      <%= link_to  @tmp_user.first_name, user_path(@tmp_user)%>
      <br>
      <%= f.body %>
      <br>
      <%  end  %>
    </td>
  </tr>
  <tr>
        <td>
          <%= form_for([post, post.comments.build]) do |f|%>
                <p>
                    <%= f.label 'your Comment' %>
                    <br>
                    <%= f.text_field :body %>
                    <%= f.submit :Comment %>
                </p>
            <%  end  %>
        </td>
  </tr>
<% end %>      
</table>


<h2>List Of Friends</h2>

<table>                         
  <tr>                          
    <th>First_name</th>
  </tr>
<% @friends.each do |friend| %>      
  <tr>
    <td><%= friend.first_name %></td>
  </tr>
<% end %>                       
</table>

</body>
</html>

app/views/users/new.html.erb
<title>SignUp</title>
</head>
<body>
<h2>Welcome to Facebook</h2>
<table>
<%= form_for :user , url: users_path do |f| %>

<tr>
    <td>
        <%= f.label :First_Name%>
    </td>
    <td>
        <%= f.text_field :first_name %>
    </td>
</tr>
<tr>
    <td>
        <%= f.label :Email %>
    </td>
    <td>
        <%= f.text_field :email_id %>
    </td>
</tr>
<tr>
    <td>
        <%= f.label :Password%>
    </td>
    <td>
        <%= f.password_field :password %>
    </td>
</tr>

<tr>
    <td>
        <%= f.label :Mobile_Number%>
    </td>
    <td>
        <%= f.text_field :mobile_number %>
    </td>
</tr>


<tr>
    <td>
        <%= f.label :College_Name%>
    </td>
    <td>
        <%= f.text_field :college %>
    </td>
</tr>
<tr>
    <td>
        <%= f.submit :SignUp  %>  
    </td>
</tr>
<% end %>
</table>
</body>
</html>

app/views/users/search_friend.html.erb
<% @searched_friends.each do |f| %>
<%= link_to f.first_name , user_path(f.id) %>
<br>
<%  end  %>

app/views/users/show.html.erb
<title>Profile</title>
</head>

<body>
    <p><%=  params[:id]  %></p><br>
    
    <% if @is_friend == false %>
    
        <%= form_for( @user, :url => add_friend_user_path( @user ), :html => { :method => :post } ) do |f| %>
        <p>Add to Friend Circle.</p>
        <%= f.submit "Add to Circle." %>
        <% end %>
    <% end %>
    
    
    <table>
        <tr>
            <th>
                First Name
            </th>
        </tr>
        <tr>
            <td>
                <%= @user.first_name%>
            </td>
        </tr>
        
    </table>
</body>
</html>